apps/appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'
urlpatterns = [
    path('', views.DoctorListView.as_view(), name='doctor_list'),
    path('primary', views.PriListView.as_view(), name='primary'),
    path('pediatric', views.PedListView.as_view(), name='pediatric'),
    path('internal', views.IntListView.as_view(), name='internal'),
    path('cardiology', views.CarListView.as_view(), name='cardiology'),
    path('neurology', views.NeuListView.as_view(), name='neurology'),
    path('ob_gy', views.OGListView.as_view(), name='ob_gy'),
    path('orthopedics', views.OrtListView.as_view(), name='orthopedics'),
    path('dermatology', views.DerListView.as_view(), name='dermatology'),
    path('<int:pk>/', views.DoctorDetailView.as_view(), name='doctor_detail'),
    path("search/", views.SearchView.as_view(), name="doctor_search"),
]

apps/chat/urls.py
from django.urls import path
from .views import *

app_name = 'chatbot'
urlpatterns = [
    path('', chatbot_view, name='chatbot'),
]

apps/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

apps/news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<int:pk>/', views.NewsDetailView.as_view(), name='news_detail'),
    path("news/search/", views.NewsSearchView.as_view(), name="news_search"),
    ]

hs/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include # Import 'include'
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.home.urls")),
    path('chat/', include("apps.chat.urls")),
    path('appointment', include("apps.appointment.urls")),
    path('news/', include('apps.news.urls')),  # News
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.shortcuts import render
from apps.appointment.models import Doctor
from apps.news.models import News


def home(request):
    news = News.objects.order_by('-published_date')[:3]
    doctor = Doctor.objects.all()[:3]
    context = {'news': news, 'doctor': doctor}
    return render(request, 'home/home.html', context)

templates/home/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>{% block title %}Online Healthcare system{% endblock %}</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
   <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/dayschedule-widget@latest/dist/dayschedule-widget.css" rel="stylesheet" type="text/css" />
      {% block css %}{% endblock %}

    <!-- Custom styles for this template -->
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md fixed-top bg-white">
        <div class="container-fluid">
         <a class="navbar-brand" href="{% url 'home:home'%}"><img src="{% static 'img/dlogo2.png' %}" alt="" width="80" height="30" class="d-inline-block align-text-top"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'appointment:doctor_list'%}">Appointment</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'chatbot:chatbot'%}">DoctorAI</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'news:news_list'%}">News</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
{#              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
{#              <button class="btn btn-outline-success" type="submit">Search</button>#}
            </form>
          </div>
        </div>
      </nav>
    </header>

    {% block content %}{% endblock %}

    <!-- FOOTER -->



    <!-- JavaScript -->
    <script  src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/dayschedule-widget@latest/dist/dayschedule-widget.min.js" defer></script>
    {% block js %}{% endblock %}
  </body>
</html>

templates/home/home.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
<main>

  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
          <img src="{% static 'img/dbg.png' %}" class="bd-placeholder-img" alt="..." width="100%" height="100%">
      </div>
    </div>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
    {% if doctor%}
      {% for doctor in doctor %}
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">
            <image xlink:href="{{doctor.photo.url }}" x="0" y="0" height="100%" width="100%" ></image>
        </svg>

        <h2 class="fw-normal">{{ doctor.name }}</h2>
        <p>{{ doctor.bio }}</p>
        <p><a class="btn btn-secondary" href="{% url 'appointment:doctor_detail' doctor.id %}">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      {% endfor %}
    {% endif %}
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">
   {%  if news %}
       {% for news in news %}
        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading fw-normal lh-1">{{ news.title }}</h2>
            <p class="lead">{{news.news_content|truncatewords:30|striptags }}</p>
          </div>
          <div class="col-md-5">
            <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false">
                <image xlink:href="{{news.cover_img.url }}" x="0" y="0" height="100%" width="100%" ></image>
            </svg>

          </div>
        </div>

        <hr class="featurette-divider">
     {% endfor %}
   {% endif %}



    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->

</main>
{% endblock %}