apps/news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<int:pk>/', views.NewsDetailView.as_view(), name='news_detail'),
    path("news/search/", views.NewsSearchView.as_view(), name="news_search"),
    ]

hs/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include # Import 'include'
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.home.urls")),
    path('chat/', include("apps.chat.urls")),
    path('appointment', include("apps.appointment.urls")),
    path('news/', include('apps.news.urls')),  # News
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/news/models.py
from django.db import models
from ckeditor.fields import RichTextField


# News model
class News(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100, blank=True, null=True)
    affiliation = models.CharField("affiliation", max_length=100, blank=True, null=True)
    external_link = models.URLField('external link', blank=True, null=True)
    published_date = models.DateTimeField("date published", auto_now=False, auto_now_add=False)  # published time
    updated_date = models.DateTimeField("date updated", auto_now=True)  # updated time for news, not show in the webpage
    news_content = RichTextField(blank=True, null=True)
    cover_img = models.ImageField("cover image", upload_to='news/')
    is_publish = models.BooleanField("publish", default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "news"  # name in the admin site
        verbose_name_plural = verbose_name

apps/news/views.py
from django.db.models import Q
from django.views import generic

from .models import News


# News list view
class NewsListView(generic.ListView):
    template_name = 'news/news_list.html'
    queryset = News.objects.filter(is_publish=True).order_by('-published_date')  # ordering by latest published time
    paginate_by = 10  # show Rural360 number in one page


# News detail View
class NewsDetailView(generic.DetailView):
    model = News
    template_name = 'news/news_detail.html'


# News search view
class NewsSearchView(generic.ListView):
    paginate_by = 10
    template_name = 'news/news_search_result.html'

# Return search result
    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = News.objects.order_by('-published_date').filter(
                Q(title__icontains=query) | Q(author__icontains=query) | Q(affiliation__icontains=query) | Q(news_content__icontains=query) | Q(published_date__icontains=query)
            )
        return object_list

# Add query content in context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        return context

templates/news/news_detail.html
{% extends 'home/base.html' %}
{% load static %}
<!--Shows news details-->
{% block content %}
<div class="container">
    <div class="card mt-4 mb-3">
      <div class="card-body">
        <h1>{{ object.title }}</h1>
        <p class=" text-muted">{{ object.author }} {% if object.external_link %}<a href="{{ object.external_link }}">{{ object.affiliation }}</a> {% else %} {{ object.affiliation }}{% endif %}| {{ object.published_date| date:"F d, Y"}}</p>
        <p class="card-text ">{{ object.news_content | safe }}</p>
      </div>
    </div>
</div>
{% endblock content %}
{% block js %}
{% endblock %}

templates/news/news_list.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
<div class = "container">
<!-- Select news type option and search rural360 news bar-->
    <div class="row mt-4">
       <div>
        <form class="d-flex" role="search" action="{% url 'news:news_search' %}" method="get">
            <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="q", required="required"/>
            <button class="btn btn-outline-dark" type="submit">Search</button>
        </form>
       </div>
    </div> <!-- end select and search-->

 <!-- Rural360 list-->
    <div>
      {% for news in page_obj %}
        <div class="card mt-3 mb-3" >
          <div class="row g-0">
            <div class="col-md-2">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">
                     <image xlink:href="{{ news.cover_img.url }}" x="0" y="5%" height="100%" width="100%" ></image>
                </svg>
            </div>
            <div class="col-md-10">
              <div class="card-body">
                <h5 class="card-title"><a href="{% url 'news:news_detail' news.id %}" style="color:#3C4245">{{ news.title }}</a></h5>
                <p class="card-text"><small class="text-muted">{{ news.author}}|{{ news.published_date| date:"F d, Y" }} </small></p>
                <p class="card-text">{{news.news_content|truncatewords:30|striptags }}</p>
              </div>
            </div>
          </div>
        </div>
     {% endfor %}
    </div>  <!-- end Rural360 list-->
<!-- pagination-->
    <div>
        {% if page_obj.paginator.num_pages > 1%}
             <nav aria-label="Page navigation example">
               <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
                    {% endif %}
                       <li class="page-item disabled" ><a class="page-link" href="?page={{ page_obj.number }}">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                   {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                   {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
                   {% endif %}
                </ul>
              </nav>
        {% endif %}
    </div><!--end pagination-->
</div>
{% endblock %}

templates/news/news_search_result.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
 <div class="container">
 <!--Rural360 news search results-->
    <div>
     <h2 class="mt-5">Search results for News</h2>
     <hr class="mt-0">
     {% for news in page_obj %}
        <div class="card mb-3 mt-3">
          <div class="row g-0">
            <div class="col-md-4">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">
                     <image xlink:href="{{news.cover_img.url }}" x="0" y="0" height="100%" width="100%" ></image>
               </svg>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><a href="{% url 'news:news_detail' news.id %}" style="color:#3C4245">{{ news.title }}</a></h5>
                <p class="card-text"><small class="text-muted">{{ news.author}}|{{ news.published_date| date:"F d, Y"}} </small></p>
                <p class="card-text">{{news.news_content|truncatewords:20|striptags }}</p>
              </div>
            </div>
          </div>
        </div>
        {% empty %}
         <h3 class="mt-5">No Results</h3>
     {% endfor %}
    </div><!--End search result-->
 <!--Pagination-->
   <div>
        {% if page_obj.paginator.num_pages > 1%}
          <nav aria-label="Page navigation example">
           <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?q={{query}}&page=1">First</a></li>
                    <li class="page-item"><a class="page-link" href="?q={{query}}&page={{ page_obj.previous_page_number }}">Prev</a></li>
               {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
               {% endif %}
                   <li class="page-item disabled" ><a class="page-link" href="?q={{query}}&page={{ page_obj.number }}">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
               {% if page_obj.has_next %}
                    <li class="page-item "><a class="page-link" href="?q={{query}}&page={{ page_obj.next_page_number }}">Next</a></li>
                    <li class="page-item "><a class="page-link" href="?q={{query}}&page={{ page_obj.paginator.num_pages }}">Last</a></li>
               {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
               {% endif %}
            </ul>
          </nav>
        {% endif %}
   </div><!--End pagination-->
</div>
{% endblock %}