apps/appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'
urlpatterns = [
    path('', views.DoctorListView.as_view(), name='doctor_list'),
    path('primary', views.PriListView.as_view(), name='primary'),
    path('pediatric', views.PedListView.as_view(), name='pediatric'),
    path('internal', views.IntListView.as_view(), name='internal'),
    path('cardiology', views.CarListView.as_view(), name='cardiology'),
    path('neurology', views.NeuListView.as_view(), name='neurology'),
    path('ob_gy', views.OGListView.as_view(), name='ob_gy'),
    path('orthopedics', views.OrtListView.as_view(), name='orthopedics'),
    path('dermatology', views.DerListView.as_view(), name='dermatology'),
    path('<int:pk>/', views.DoctorDetailView.as_view(), name='doctor_detail'),
    path("search/", views.SearchView.as_view(), name="doctor_search"),
]

hs/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include # Import 'include'
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.home.urls")),
    path('chat/', include("apps.chat.urls")),
    path('appointment', include("apps.appointment.urls")),
    path('news/', include('apps.news.urls')),  # News
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/appointment/models.py
from django.db import models


class Doctor(models.Model):
    DEPARTMENT_CHOICES = [
        ('primary_care', 'Primary Care'),
        ('pediatrics', 'Pediatrics'),
        ('internal_medicine', 'Internal Medicine'),
        ('cardiology', 'Cardiology'),
        ('neurology', 'Neurology'),
        ('ob_gyn', 'Obstetrics and Gynecology'),
        ('orthopedics', 'Orthopedics'),
        ('dermatology', 'Dermatology'),
    ]
    name = models.CharField(max_length=255)
    department = models.CharField(max_length=255, choices=DEPARTMENT_CHOICES)
    specialization = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    bio = models.TextField()
    photo = models.ImageField(upload_to='doctors/', default='static/img/avatar.png')
    url = models.URLField()

    def __str__(self):
        return self.name

apps/appointment/views.py
from django.shortcuts import render
from django.views import generic
from django.db.models import Q
from .models import Doctor


# all doctor list view
class DoctorListView(generic.ListView):
    template_name = 'appointment/doctor_list.html'
    queryset = Doctor.objects.all()
    paginate_by = 6


# List view
class PriListView(generic.ListView):
    template_name = 'appointment/primary_care.html'
    queryset = Doctor.objects.filter(department='primary_care')
    paginate_by = 6


# List view
class PedListView(generic.ListView):
    template_name = 'appointment/pediatrics.html'
    queryset = Doctor.objects.filter(department='pediatrics')
    paginate_by = 6


# List view
class IntListView(generic.ListView):
    template_name = 'appointment/internal_medicine.html'
    queryset = Doctor.objects.filter(department='internal_medicine')
    paginate_by = 6


# List view
class CarListView(generic.ListView):
    template_name = 'appointment/cardiology.html'
    queryset = Doctor.objects.filter(department='cardiology')
    paginate_by = 6


# List view
class NeuListView(generic.ListView):
    template_name = 'appointment/neurology.html'
    queryset = Doctor.objects.filter(department='neurology')
    paginate_by = 6


# List view
class OGListView(generic.ListView):
    template_name = 'appointment/ob_gyn.html'
    queryset = Doctor.objects.filter(department='ob_gyn')
    paginate_by = 6


# List view
class OrtListView(generic.ListView):
    template_name = 'appointment/orthopedics.html'
    queryset = Doctor.objects.filter(department='orthopedics')
    paginate_by = 6


# List view
class DerListView(generic.ListView):
    template_name = 'appointment/dermatology.html'
    queryset = Doctor.objects.filter(department='dermatology')
    paginate_by = 6

# Doctor Detail View
class DoctorDetailView(generic.DetailView):
    model = Doctor
    template_name = 'appointment/doctor_detail.html'


# Search view
class SearchView(generic.ListView):
    paginate_by = 6
    template_name = 'appointment/search_result.html'

# return search Rural360 result
    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Doctor.objects.filter(
                Q(name__icontains=query) | Q(specialization__icontains=query) | Q(department__icontains=query)
            )
        return object_list

# add query content in  context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        return context

templates/appointment/cardiology.html
{% extends "appointment/doctor_base.html" %}
{% load static %}
{%block doctor %}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Cardiology</h1>
            <div class="mb-2 mb-md-0">
            <form class="d-flex mt-3" role="search" action="{% url "appointment:doctor_search" %}" method="get">
                <input class="myInput form-control me-2" type="text" placeholder="Search" aria-label="Search" name="q", required="required"/>
                <button class="myBtn btn btn-outline-dark" type="submit">Search</button>
            </form>
            </div>
          </div>
          <div>
        <div class="container mt-5">
        <div class="row row-cols-3">
            {% for obj in page_obj %}
              <div class="col">
               {% if obj.photo %}
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <image xlink:href="{{ obj.photo.url }}" x="0" y="0" height="100%" width="100%" ></image>
                </svg>
               {% endif %}
                <h3 class="fw-normal"><a class="link-dark " href="{% url 'appointment:doctor_detail' obj.id%}">{{ obj.name}}</a></h3>
                <p>{{ obj.specialization }} |  <a href="#" onclick="openPopupWidget('{{obj.url}}')">Booking</a></p>
                <br><br>
              </div> <!-- /.col-lg-4 -->
            {% endfor %}
        </div><!-- /.row -->
<!-- pagination-->
    <div class="mt-5">
        {% if page_obj.paginator.num_pages > 1%}
             <nav aria-label="Page navigation example">
               <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
                   {% endif %}
                       <li class="page-item disabled" ><a class="page-link" href="?page={{ page_obj.number }}">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                   {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
                   {% endif %}
               </ul>
             </nav>
        {% endif %}
    </div><!--end pagination-->
  </div>
          </div>
    </main>
<script>
function openPopupWidget(url) {
   daySchedule.initPopupWidget({
      url: url,
      color: {
      primary: '#46B9CC',
      secondary: '#afeefe'
  }
});
}
</script>
{% endblock %}

templates/appointment/dermatology.html
{% extends "appointment/doctor_base.html" %}
{% load static %}
{%block doctor %}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dermatology</h1>
            <div class="mb-2 mb-md-0">
            <form class="d-flex mt-3" role="search" action="{% url "appointment:doctor_search" %}" method="get">
                <input class="myInput form-control me-2" type="text" placeholder="Search" aria-label="Search" name="q", required="required"/>
                <button class="myBtn btn btn-outline-dark" type="submit">Search</button>
            </form>
            </div>
          </div>
          <div>
        <div class="container mt-5">
        <div class="row row-cols-3">
            {% for obj in page_obj %}
              <div class="col">
               {% if obj.photo %}
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <image xlink:href="{{ obj.photo.url }}" x="0" y="0" height="100%" width="100%" ></image>
                </svg>
               {% endif %}
                <h3 class="fw-normal"><a class="link-dark " href="{% url 'appointment:doctor_detail' obj.id%}">{{ obj.name}}</a></h3>
                <p>{{ obj.specialization }} |  <a href="#" onclick="openPopupWidget('{{obj.url}}')">Booking</a></p>
                <br><br>
              </div> <!-- /.col-lg-4 -->
            {% endfor %}
        </div><!-- /.row -->
<!-- pagination-->
    <div class="mt-5">
        {% if page_obj.paginator.num_pages > 1%}
             <nav aria-label="Page navigation example">
               <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
                   {% endif %}
                       <li class="page-item disabled" ><a class="page-link" href="?page={{ page_obj.number }}">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                   {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
                   {% endif %}
               </ul>
             </nav>
        {% endif %}
    </div><!--end pagination-->
  </div>
          </div>
    </main>
<script>
function openPopupWidget(url) {
   daySchedule.initPopupWidget({
      url: url,
      color: {
      primary: '#46B9CC',
      secondary: '#afeefe'
  }
});
}
</script>
{% endblock %}

templates/appointment/doctor_base.html
{% extends "home/home.html" %}
{% load static %}
{% block css %}
    <style>
        .feather {
          width: 16px;
          height: 16px;
        }

        /*
         * Sidebar
         */

        .sidebar {
          position: fixed;
          top: 0;
          /* rtl:raw:
          right: 0;
          */
          bottom: 0;
          /* rtl:remove */
          left: 0;
          z-index: 100; /* Behind the navbar */
          padding: 48px 0 0; /* Height of navbar */
          box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
        }

        @media (max-width: 767.98px) {
          .sidebar {
            top: 5rem;
          }
        }

        .sidebar-sticky {
          position: relative;
          top: 0;
          height: calc(100vh - 48px);
          padding-top: .5rem;
          overflow-x: hidden;
          overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
        }

        .sidebar .nav-link {
          font-weight: 500;
          color: #333;
        }

        .sidebar .nav-link .feather {
          margin-right: 4px;
          color: #727272;
        }

        .sidebar .nav-link.active {
          color: #2470dc;
        }

        .sidebar .nav-link:hover .feather,
        .sidebar .nav-link.active .feather {
          color: inherit;
        }

        .sidebar-heading {
          font-size: .75rem;
        }

    </style>
{% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url "appointment:doctor_list" %}">
              <span data-feather="home" class="align-text-bottom"></span>
              ALL
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "appointment:primary" %}">
              <span data-feather="file" class="align-text-bottom"></span>
              Primary Care
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "appointment:pediatric" %}">
              <span data-feather="shopping-cart" class="align-text-bottom"></span>
              Pediatrics
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "appointment:internal" %}">
              <span data-feather="users" class="align-text-bottom"></span>
              Internal Medicine
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "appointment:cardiology" %}">
              <span data-feather="bar-chart-2" class="align-text-bottom"></span>
              Cardiology
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "appointment:neurology" %}">
              <span data-feather="layers" class="align-text-bottom"></span>
              Neurology
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "appointment:ob_gy" %}">
              <span data-feather="layers" class="align-text-bottom"></span>
              Obstetrics and Gynecology
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "appointment:orthopedics" %}">
              <span data-feather="layers" class="align-text-bottom"></span>
              Orthopedics
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "appointment:dermatology" %}">
              <span data-feather="layers" class="align-text-bottom"></span>
              Dermatology
            </a>
          </li>
        </ul>
      </div>
    </nav>
{% block doctor %}
{% endblock %}

  </div>
</div>
{% endblock %}

templates/appointment/doctor_list.html
{% extends "appointment/doctor_base.html" %}
{% load static %}
{%block doctor %}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">All Doctor</h1>
            <div class="mb-2 mb-md-0">
            <form class="d-flex mt-3" role="search" action="{% url "appointment:doctor_search" %}" method="get">
                <input class="myInput form-control me-2" type="text" placeholder="Search" aria-label="Search" name="q", required="required"/>
                <button class="myBtn btn btn-outline-dark" type="submit">Search</button>
            </form>
            </div>
          </div>
          <div>
        <div class="container mt-5">
        <div class="row row-cols-3">
            {% for obj in page_obj %}
              <div class="col">
               {% if obj.photo %}
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <image xlink:href="{{ obj.photo.url }}" x="0" y="0" height="100%" width="100%" ></image>
                </svg>
               {% endif %}
                <h3 class="fw-normal"><a class="link-dark " href="{% url 'appointment:doctor_detail' obj.id%}">{{ obj.name}}</a></h3>
                <p>{{ obj.specialization }} |  <a href="#" onclick="openPopupWidget('{{obj.url}}')">Booking</a></p>
                <br><br>
              </div> <!-- /.col-lg-4 -->
            {% endfor %}
        </div><!-- /.row -->
<!-- pagination-->
    <div class="mt-5">
        {% if page_obj.paginator.num_pages > 1%}
             <nav aria-label="Page navigation example">
               <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
                   {% endif %}
                       <li class="page-item disabled" ><a class="page-link" href="?page={{ page_obj.number }}">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                   {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
                   {% endif %}
               </ul>
             </nav>
        {% endif %}
    </div><!--end pagination-->
  </div>
          </div>
    </main>
<script>
function openPopupWidget(url) {
   daySchedule.initPopupWidget({
      url: url,
      color: {
      primary: '#46B9CC',
      secondary: '#afeefe'
  }
});
}
</script>
{% endblock %}

templates/appointment/internal_medicine.html
{% extends "appointment/doctor_base.html" %}
{% load static %}
{%block doctor %}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Internal medicine</h1>
            <div class="mb-2 mb-md-0">
            <form class="d-flex mt-3" role="search" action="{% url "appointment:doctor_search" %}" method="get">
                <input class="myInput form-control me-2" type="text" placeholder="Search" aria-label="Search" name="q", required="required"/>
                <button class="myBtn btn btn-outline-dark" type="submit">Search</button>
            </form>
            </div>
          </div>
          <div>
        <div class="container mt-5">
        <div class="row row-cols-3">
            {% for obj in page_obj %}
              <div class="col">
               {% if obj.photo %}
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <image xlink:href="{{ obj.photo.url }}" x="0" y="0" height="100%" width="100%" ></image>
                </svg>
               {% endif %}
                <h3 class="fw-normal"><a class="link-dark " href="{% url 'appointment:doctor_detail' obj.id%}">{{ obj.name}}</a></h3>
                <p>{{ obj.specialization }} |  <a href="#" onclick="openPopupWidget('{{obj.url}}')">Booking</a></p>
                <br><br>
              </div> <!-- /.col-lg-4 -->
            {% endfor %}
        </div><!-- /.row -->
<!-- pagination-->
    <div class="mt-5">
        {% if page_obj.paginator.num_pages > 1%}
             <nav aria-label="Page navigation example">
               <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
                   {% endif %}
                       <li class="page-item disabled" ><a class="page-link" href="?page={{ page_obj.number }}">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                   {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
                   {% endif %}
               </ul>
             </nav>
        {% endif %}
    </div><!--end pagination-->
  </div>
          </div>
    </main>
<script>
function openPopupWidget(url) {
   daySchedule.initPopupWidget({
      url: url,
      color: {
      primary: '#46B9CC',
      secondary: '#afeefe'
  }
});
}
</script>
{% endblock %}

templates/appointment/neurology.html
{% extends "appointment/doctor_base.html" %}
{% load static %}
{%block doctor %}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Neurology</h1>
            <div class="mb-2 mb-md-0">
            <form class="d-flex mt-3" role="search" action="{% url "appointment:doctor_search" %}" method="get">
                <input class="myInput form-control me-2" type="text" placeholder="Search" aria-label="Search" name="q", required="required"/>
                <button class="myBtn btn btn-outline-dark" type="submit">Search</button>
            </form>
            </div>
          </div>
          <div>
        <div class="container mt-5">
        <div class="row row-cols-3">
            {% for obj in page_obj %}
              <div class="col">
               {% if obj.photo %}
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <image xlink:href="{{ obj.photo.url }}" x="0" y="0" height="100%" width="100%" ></image>
                </svg>
               {% endif %}
                <h3 class="fw-normal"><a class="link-dark " href="{% url 'appointment:doctor_detail' obj.id%}">{{ obj.name}}</a></h3>
                <p>{{ obj.specialization }} |  <a href="#" onclick="openPopupWidget('{{obj.url}}')">Booking</a></p>
                <br><br>
              </div> <!-- /.col-lg-4 -->
            {% endfor %}
        </div><!-- /.row -->
<!-- pagination-->
    <div class="mt-5">
        {% if page_obj.paginator.num_pages > 1%}
             <nav aria-label="Page navigation example">
               <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
                   {% endif %}
                       <li class="page-item disabled" ><a class="page-link" href="?page={{ page_obj.number }}">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                   {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
                   {% endif %}
               </ul>
             </nav>
        {% endif %}
    </div><!--end pagination-->
  </div>
          </div>
    </main>
<script>
function openPopupWidget(url) {
   daySchedule.initPopupWidget({
      url: url,
      color: {
      primary: '#46B9CC',
      secondary: '#afeefe'
  }
});
}
</script>
{% endblock %}

templates/appointment/search_result.html
{% extends "appointment/doctor_base.html" %}
{% load static %}
{%block doctor %}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Search Result</h1>
          </div>
          <div>
        <div class="container mt-5">
        <div class="row row-cols-3">
            {% for obj in page_obj %}
              <div class="col">
               {% if obj.photo %}
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <image xlink:href="{{ obj.photo.url }}" x="0" y="0" height="100%" width="100%" ></image>
                </svg>
               {% endif %}
                <h3 class="fw-normal"><a class="link-dark " href="{% url 'appointment:doctor_detail' obj.id%}">{{ obj.name}}</a></h3>
                <p>{{ obj.specialization }} |  <a href="#" onclick="openPopupWidget('{{obj.url}}')">Booking</a></p>
                <br><br>
              </div> <!-- /.col-lg-4 -->
            {% endfor %}
        </div><!-- /.row -->
<!-- pagination-->
    <div class="mt-5">
        {% if page_obj.paginator.num_pages > 1%}
             <nav aria-label="Page navigation example">
               <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Prev</a></li>
                   {% endif %}
                       <li class="page-item disabled" ><a class="page-link" href="?page={{ page_obj.number }}">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                   {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
                   {% endif %}
               </ul>
             </nav>
        {% endif %}
    </div><!--end pagination-->
  </div>
          </div>
    </main>
<script>
function openPopupWidget(url) {
   daySchedule.initPopupWidget({
      url: url,
      color: {
      primary: '#46B9CC',
      secondary: '#afeefe'
  }
});
}
</script>
{% endblock %}